---
service: verifyer
frameworkVersion: '3'

provider:
  name: aws
  region: eu-north-1
  runtime: python3.9

functions:
  hello:
    handler: handler.hello
    package:
      # Directories and files to include in the deployed package
      patterns:
        - '*.csv'
    events:
      - httpApi:
          path: /
          method: get
...
